name: clock

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: 45 13 * * *

jobs:
  bot:
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout codes'
      uses: actions/checkout@v1
    - name: 'Set up Python'
      uses: actions/setup-python@v1
      with:
        python-version: '3.8'
    - name: 'Install requirements'
      run: |
        pip install -r requirements.txt
 
    - name: Run
      run: |
        python3 index.py <<EOF
        ${{secrets.PHONE}}
        ${{secrets.PASSWORD}}
        ${{secrets.PPHONE}}
        ${{secrets.PNAME}}
        ${{secrets.AREASTR}}
        ${{secrets.SCKEY}}
        EOF
